name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: '01'
      MYREPO: ${{ secrets.MYREPO }} 
      MYIMAGE: ${{ secrets.MYIMAGE }}
      TL_USER: ${{ secrets.TL_USER }}
      TL_PASS: ${{ secrets.TL_PASS }}
      TL_CONSOLE_URL: ${{ secrets.TL_CONSOLE_URL }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PW: ${{ secrets.DOCKER_PW }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $MYREPO/$MYIMAGE:$TAG
    - name: Scan the Docker image
      run: |
        curl -k -u $TL_USER:$TL_PASS --output ./twistcli $TL_CONSOLE_URL/api/v1/util/twistcli
        chmod a+x ./twistcli
        ./twistcli images scan \
          --details \
          -address $TL_CONSOLE_URL \
          -u $TL_USER \
          -p $TL_PASS \
          --vulnerability-threshold high \
          --compliance-threshold high \
          $MYREPO/$MYIMAGE:$TAG
    - name: Push the Docker image
      run: |
        echo $DOCKER_PW | docker login --username $DOCKER_USER --password-stdin docker.io
        docker push docker.io/$MYREPO/$MYIMAGE:$TAG
